
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hylur-knowledge-foundation:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hylur-knowledge-foundation:$COMMIT_SHA']
  
  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Node.js and npm
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        
        # Navigate to app directory and install dependencies
        cd app
        npm install
        
        # Run Prisma migrations
        npx prisma migrate deploy
        
        # Run seed script if it exists
        if [ -f "scripts/seed.ts" ]; then
          npx tsx scripts/seed.ts
        fi
    env:
      - 'DATABASE_URL=$$DATABASE_URL'
    secretEnv: ['DATABASE_URL']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hylur-knowledge-foundation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hylur-knowledge-foundation:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,ABACUSAI_API_KEY=ABACUSAI_API_KEY:latest'
      - '--set-env-vars'
      - 'NEXTAUTH_URL=https://hylur.net'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

images:
  - 'gcr.io/$PROJECT_ID/hylur-knowledge-foundation:$COMMIT_SHA'
